# version: "3.5"
# services:
#     account:
     
#         build:
#             context: .
#         container_name : chat_account
#         networks :
#             - chat_network
#         env_file:
#             - ./envs/development.env
#         ports:
#             - 8001:8001
#         volumes:
#             # - ./:/app
#             - /store/account/media:/app/media
#             - /store/account/static:/app/static

#         # command:
#             # gunicorn account.wsgi:application --reload --bind 0.0.0.0:8000 --timeout 600 
#         command: python manage.py runserver 0.0.0.0:8001
          
        
    
#     account-database:
#         image: postgres:alpine

#         env_file:
#             - ./envs/development.db.env
    

# volumes:
#     account-media:
#     account-static:

# networks:
#     chat_network:
#         driver : bridge



version: '3.5'

services:
  account:
    build: .
    working_dir: /app/app
    command: sh -c 'python manage.py runserver 0.0.0.0:8001'
    volumes:
      - .:/app/app
    ports:
      - 8001:8001
    environment:
      - DATABASE_URL=postgresql://django:django@db:5432/django
    depends_on:
      - db
 
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=django
  
  

volumes:
  postgres_data:

networks:
  default:
    external: true
    name: chat

  
